default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: raaather_development

test:
  <<: *default
  database: raaather_test

production:
  <<: *default
  database: raaather_production
  username: raaather
  password: <%= ENV['EXAMPLE_DATABASE_PASSWORD'] %>
